name: slackSend

inputs:
  status:
    type: boolean
    required: false
    default: false
  slackURL:
    required: true

runs:
  using: "composite"
  steps:
    - name: slack step
      shell: bash
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"전체 브랜드 디플로이 완료:+1:, ${{ inputs.status }} ${{ inputs.slackURL }}"}' https://hooks.slack.com/services/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