name: work

on:
  push:
    branches:
      - main
d
jobs:
  Work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: work step
        if: always()
        uses: ./.github/actions/slackSend
        with:
          status: ${{job.status}}